---
name: Semantic Release
on:
  push:
    branches:
      - main

jobs:
  all:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
